import type { Metadata } from "next";
// import openSansRegular from "../../public/fonts/OpenSans-Regular.ttf"
// import openSansMedium from "../../public/fonts/OpenSans-Medium.ttf"
// import openSansBold from "../../public/fonts/OpenSans-Bold.ttf"
import { Open_Sans } from 'next/font/google'

const openSans = Open_Sans({
  subsets: ['latin'],
  // Optional: specify weights you plan to use
  weight: ['300', '400', '500', '600', '700'],
  // Optional: if you want to use it as a CSS variable
  variable: '--font-opensans',
})
import "./globals.css";

// const sansRegular = openSansRegular({
//   variable: "--font-sans-regular",
// });

// const sansMedium = openSansMedium({
//   variable: "--font-sans-medium",
// });

// const sansBold = openSansBold({
//   variable: "--font-sans-bold",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSans.variable}`}>
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
